version: '3.7'

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: "65535"
      net.ipv4.tcp_max_syn_backlog: "65535"
    #user: "101:101" # Запуск от nginx (UID/GID 101)
    networks:
      - vpn_net
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
      - "5555:5555"
    env_file:
      - ./nginx/.env
    volumes:
      - ./nginx/auth:/etc/nginx/auth:ro
      - ./certs/:/etc/letsencrypt/:ro
    labels:
      - "com.docker.compose.project=vovonevpn"

  x-ui:
    build: ./3x-ui
    image: x-ui
    container_name: x-ui
    restart: unless-stopped
    user: "0:0"  # Запуск от root (UID=0)
    networks:
      - vpn_net
    expose:
      - "2053/tcp"   # Дефолтный для панели
      - "5580/tcp"    # Панель
      - "5555/tcp"   # Подписки
    ports:
      - "6443:6443"
    volumes:
      - ./3x-ui/data/config/config.json:/app/bin/config.json # Для config.json
      - ./3x-ui/data/db/x-ui.db:/etc/x-ui/x-ui.db # Для x-ui.db
      - ./certs:/root/cert:ro
      - ./3x-ui/data/config/fail2ban.local:/etc/fail2ban/fail2ban.local
    environment:
      - XUI_LOG_LEVEL=debug
      - XUI_APP_FOLDER=/app
      - XUI_BIN_FOLDER=/app/bin
      - XUI_DB_FOLDER=/etc/x-ui
      - XUI_LOG_FOLDER=/var/log/x-ui
      - X_UI_ENABLE_FAIL2BAN=true
    labels:
      - "com.docker.compose.project=vovonevpn"

  # Контейнер для бэкапов
  x-ui-backup:
    image: alpine
    container_name: x-ui-backup
    restart: unless-stopped
    depends_on:
      - x-ui
    volumes:
      - /vovOneVPN/3x-ui/data:/x-ui-data:ro
      - /vovOneVPN/3x-ui/backups:/backups
    command: >
      sh -c '
        apk add --no-cache tar findutils;
        while true; do
          sleep 3600;
          TIMESTAMP=$$(date +%Y-%m-%d_%H-%M-%S);
          tar -czvf /backups/x-ui-backup-$$TIMESTAMP.tar.gz /x-ui-data/config/config.json /x-ui-data/db/x-ui.db;
          find /backups -name "x-ui-backup-*.tar.gz" -mtime +7 -delete;
          echo "Backup created: x-ui-backup-$$TIMESTAMP.tar.gz";
        done
      '
    labels:
      - "com.docker.compose.project=vovonevpn"

  pritunl:
    image: ghcr.io/jippi/docker-pritunl:latest
    container_name: pritunl
    restart: unless-stopped
    networks:
      - vpn_net
    expose:
      - "500/udp"
      - "4500/udp"
      - "9700/tcp"
    volumes:
      - ./pritunl/data:/var/lib/mongodb
    environment:
      TZ: "Europe/Moscow"
    labels:
      - "com.docker.compose.project=vovonevpn"

networks:
  vpn_net:
    driver: bridge
    labels:
      - "com.docker.compose.project=vovonevpn"