# ./pritunl/docker-compose.yml
version: '3.7'

services:
  pritunl:
    image: ghcr.io/jippi/docker-pritunl:latest
    container_name: pritunl
    restart: unless-stopped
    privileged: true
    networks:
      - vpn_net
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./data:/var/lib/mongodb
    environment:
      TZ: "Europe/Moscow"

networks:
  vpn_net:
    external: true